[project]
name = "readit"
version = "0.1.0"
description = "ReadIt - A book tracker"
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.17.2",
    "fastapi>=0.122.0",
    "psycopg>=3.3.2",
    "ruff>=0.14.7",
    "sqlalchemy>=2.0.44",
    "uvicorn>=0.38.0",
]
